### ISSUE TITLE
Logcat错误提示：

### ISSUE THREAD

**Issue by totemtec** [lilongweidev/MapDemo#1]
com.llw.mapdemo E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/com.llw.mapdemo/shared_prefs/authStatus_com.llw.mapdemo***********.xml

授权了仍然是这样

MIUI9.6, Android 8.1

排查了一下是 SDKInitializer.initialize(this);
这句里的问题，没法跟进去了

**Comment by lilongweidev** [comment]
你现在是地图不显示还是怎么样呢？还有其他的现象吗?因为我运行时是正常的。

**Comment by totemtec** [comment]
运行是正常的，只有Logcat报错

**Comment by lilongweidev** [comment]
Logcat日志就是你上面说的那些吗？那你现在地图能显示吗？可以定位到你当前地址吗？如果都可以的话？那你的问题就是Logcat报错吗？

**Comment by totemtec** [comment]
啥都不干，只调用一句话SDKInitializer.initialize(this);
就会报错，我再调试看看

**Comment by lilongweidev** [comment]
如果你调用这句话报错，那就说明你的项目配置存在问题，你看看文章中的配置，重点是SDK的配置，着重看AndroidManifest.xml和app的build.gradle中的改动。

**Comment by totemtec** [comment]
我用的就是你的代码

**Comment by lilongweidev** [comment]
可我运行我自己的代码的时候一切正常啊，没有你说的这个问题啊

**Comment by totemtec** [comment]
2020-12-25 15:58:27.590 25337-25337/com.llw.mapdemo E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/com.llw.mapdemo/shared_prefs/authStatus_com.llw.mapdemo��������������������������������������������������������������������������������������������������������������������������.xml
2020-12-25 15:58:27.591 25337-25337/com.llw.mapdemo E/PermissionCheck: permission check result is: 601
2020-12-25 15:58:27.595 25337-25337/com.llw.mapdemo W/System.err: java.io.IOException: Permission denied
2020-12-25 15:58:27.595 25337-25337/com.llw.mapdemo W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2020-12-25 15:58:27.595 25337-25337/com.llw.mapdemo W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
2020-12-25 15:58:27.596 25337-25337/com.llw.mapdemo W/System.err:     at java.io.File.createNewFile(File.java:1000)
2020-12-25 15:58:27.596 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapsdkplatform.comapi.util.g.a(Unknown Source:32)
2020-12-25 15:58:27.596 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapsdkplatform.comapi.util.g.a(Unknown Source:4)
2020-12-25 15:58:27.596 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapsdkplatform.comapi.util.g.a(Unknown Source:124)
2020-12-25 15:58:27.596 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapapi.common.EnvironmentUtilities.initAppDirectory(Unknown Source:12)
2020-12-25 15:58:27.596 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapsdkplatform.comapi.c.a(Unknown Source:46)
2020-12-25 15:58:27.596 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source:2)
2020-12-25 15:58:27.596 25337-25337/com.llw.mapdemo W/System.err:     at com.llw.mapdemo.MapApplication.onCreate(MapApplication.java:14)
2020-12-25 15:58:27.596 25337-25337/com.llw.mapdemo W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
2020-12-25 15:58:27.596 25337-25337/com.llw.mapdemo W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5832)
2020-12-25 15:58:27.597 25337-25337/com.llw.mapdemo W/System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
2020-12-25 15:58:27.597 25337-25337/com.llw.mapdemo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
2020-12-25 15:58:27.597 25337-25337/com.llw.mapdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-12-25 15:58:27.597 25337-25337/com.llw.mapdemo W/System.err:     at android.os.Looper.loop(Looper.java:171)
2020-12-25 15:58:27.597 25337-25337/com.llw.mapdemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6642)
2020-12-25 15:58:27.597 25337-25337/com.llw.mapdemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-25 15:58:27.597 25337-25337/com.llw.mapdemo W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
2020-12-25 15:58:27.597 25337-25337/com.llw.mapdemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2020-12-25 15:58:27.598 25337-25337/com.llw.mapdemo W/System.err: java.io.IOException: Permission denied
2020-12-25 15:58:27.598 25337-25337/com.llw.mapdemo W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2020-12-25 15:58:27.598 25337-25337/com.llw.mapdemo W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
2020-12-25 15:58:27.599 25337-25337/com.llw.mapdemo W/System.err:     at java.io.File.createNewFile(File.java:1000)
2020-12-25 15:58:27.599 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapsdkplatform.comapi.util.g.a(Unknown Source:32)
2020-12-25 15:58:27.599 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapsdkplatform.comapi.util.g.a(Unknown Source:168)
2020-12-25 15:58:27.599 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapapi.common.EnvironmentUtilities.initAppDirectory(Unknown Source:12)
2020-12-25 15:58:27.599 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapsdkplatform.comapi.c.a(Unknown Source:46)
2020-12-25 15:58:27.599 25337-25337/com.llw.mapdemo W/System.err:     at com.baidu.mapapi.SDKInitializer.initialize(Unknown Source:2)
2020-12-25 15:58:27.599 25337-25337/com.llw.mapdemo W/System.err:     at com.llw.mapdemo.MapApplication.onCreate(MapApplication.java:14)
2020-12-25 15:58:27.599 25337-25337/com.llw.mapdemo W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
2020-12-25 15:58:27.599 25337-25337/com.llw.mapdemo W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5832)
2020-12-25 15:58:27.600 25337-25337/com.llw.mapdemo W/System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
2020-12-25 15:58:27.600 25337-25337/com.llw.mapdemo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
2020-12-25 15:58:27.600 25337-25337/com.llw.mapdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-12-25 15:58:27.600 25337-25337/com.llw.mapdemo W/System.err:     at android.os.Looper.loop(Looper.java:171)
2020-12-25 15:58:27.600 25337-25337/com.llw.mapdemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6642)
2020-12-25 15:58:27.600 25337-25337/com.llw.mapdemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-25 15:58:27.601 25337-25337/com.llw.mapdemo W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
2020-12-25 15:58:27.601 25337-25337/com.llw.mapdemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by totemtec** [comment]
只报错，没看到影响功能的问题，可以先放着

**Comment by lilongweidev** [comment]
这个报错应该是SDK内部也有文件读写的需要涉及到Android的私密文件的读写，然后就是SDK中的权限检查，不过如果你非要搞清楚也很简单，你运行百度的官方Demo，看会不会有这样错误日志，如果都有那就没有什么好说的，如果它的没有，你就可以提交工单询问原因，你这个精神还是蛮可贵的。
